### ISSUE TITLE
Question: How to add indexes?

### ISSUE THREAD

**Issue by elvis197686** [RedisGraph/JRedisGraph#28]
I have tried to add an index programmatically using jredisgraph (version 1.0.3), but it crashes with an IndexOutOfBoundsException (see below). Is this the right/only way to add indexes from code?

The exception occurs when executing following code. It appears to occur because the return value from the server has only one entry, but 2 are expected.

Code:
```
    RedisGraphAPI graphApi = new RedisGraphAPI("graphKey");
    graphApi.query("CREATE INDEX on :SELECTION(id)");
```

Stack trace:
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.redislabs.redisgraph.impl.ResultSetImpl.<init>(ResultSetImpl.java:23)
	at com.redislabs.redisgraph.RedisGraphAPI.query(RedisGraphAPI.java:58)
        ....
```

**Comment by bwf93** [comment]
+1

**Comment by mklos** [comment]
+1

**Comment by jkxplg** [comment]
Hey guys, any updates on this?

**Comment by WitchsCat** [comment]
Hello Guys, sorry my first post
the same problem work around is something like

`      
final RedisGraphAPI redisGraphAPI = new RedisGraphAPI(tenantId, jedisPool);
final Client jedisClient = jedisPool.getResource().getClient()
jedisClient.sendCommand(Command.QUERY, indexQueryBuilder.build());
`

`/** @author dma on 03.01.19. */
public class CypherIndexQueryBuilder {

  private StringBuilder query = new StringBuilder();

  public void addIndex(String nodeType, String idField) {
    if (query.length() != 0) {
      query.append("\n");
    }
    query.append("CREATE INDEX ON :").append(nodeType).append("(").append(idField).append(")");
  }

  public String build() {
    return query.toString();
  }
}
`

**Comment by gkorland** [comment]
@WitchsCat index creation is supported since 1.0.5
