### ISSUE TITLE
MERGE Relationship

### ISSUE THREAD

**Issue by twallace-apptium** [RedisGraph/JRedisGraph#29]
MATCH(a:person{name:'roi'}), (b:person{name:'amit'}) MERGE (a)-[:knows]->(b) throws 
(error) Syntax error at offset 59 near 'MERGE

Q. Does CREATE, in this instance using JRedisGraph, behavior as specified in Cypher, it will re-create the relationship each time?

**Comment by gkorland** [comment]
See https://github.com/RedisLabsModules/RedisGraph/issues/185
