### ISSUE TITLE
How to use MULTI/EXEC?

### ISSUE THREAD

**Issue by jkxplg** [RedisGraph/JRedisGraph#34]
Thanks for this project.

Seeing that RedisGraph is a Redis module, I understand that we can use the MULTI/EXEC commands to query the graph as well.
How can this be done using JRedisGraph?

**Comment by kant111** [comment]
Looking for same!

**Comment by elvis197686** [comment]
The graph has been updated to support MULTI/EXEC so I think the graph client should support it (assuming it doesn't already - I couldn't find a way of doing it)

**Comment by jkxplg** [comment]
Hi, any updates about on after the changes made fto the client to support the new result set?

Thanks

**Comment by DvirDukhan** [comment]
@jkxplg I would like the get your response for the following modifications, so I can start working on them.
In order for JRedisGraph  to support MULTI/EXEC I will extend Jedis Transaction (Multi) object, so it will support graph query, delete and call procedure. This should allow you to have a familiar interface of Jedis Transaction to work with for MULTI/EXEC.

**Comment by jkxplg** [comment]
@DvirDukhan I think that this approach should be enough to support the features currently supported by RedisGraph.  Just to clarify, this will still enable retrieving the results of actions that have a return value, right?

**Comment by DvirDukhan** [comment]
@jkxplg if you mean by getting a result set of a query during MULTI/EXEC, then, yes. This is what I'm planning to achieve with this implementation.
I will start working on this soon.

**Comment by DvirDukhan** [comment]
hi @jkxplg 
JRedisGraph rc2 now support WATCH/MULTI/EXEC
