### ISSUE TITLE
Get GraphEntity properties map

### ISSUE THREAD

**Issue by jkxplg** [RedisGraph/JRedisGraph#38]
Hi,

Thanks for this project! 

When running a query and getting a node/edge in the response, there is no way of iterating over all the properties. This might be useful when I'm not interested in a set of particular properties but rather in all properties. 
I think that exposing the properties map (or at least the keys) should solve this.

**Comment by DvirDukhan** [comment]
@jkxplg property names are now available. Note that this snapshot's package structure is a bit different than the previous commit so you might need to adjust.
