### ISSUE TITLE
Timestamp values are deserialized into Integer

### ISSUE THREAD

**Issue by xujiaxj** [RedisGraph/JRedisGraph#72]
Steps to reproduce:
- run a Cypher query to create a node, with a timestamp property created like 
`MERGE (n:Foo) ON CREATE SET n.created=timestamp()`
- If you check out the graph in RedisInsight, you can see the `created` being a Unix timestamp
- If you use JRedisGraph client to retrieve the node, you will notice that the `created` property is deserialized into an integer. Because a 64-bit Unix timestamp cannot fit into a 32-bit Java integer, it overflows and yields some strange integer values.

[RedisGraph](https://oss.redislabs.com/redisgraph/cypher_support/) says the numeric types could be either 64-bit doubles and 64-bit signed integer. In Java, 64-bit signed Integer should be `Long`, instead of `Integer`. The [ResultSetScalarTypes](https://github.com/RedisGraph/JRedisGraph/blob/master/src/main/java/com/redislabs/redisgraph/impl/resultset/ResultSetScalarTypes.java) should really contain `VALUE_LONG` instead of `VALUE_INTEGER`. Likewise, In [ResultSetImpl#deserializeScalar](https://github.com/RedisGraph/JRedisGraph/blob/master/src/main/java/com/redislabs/redisgraph/impl/resultset/ResultSetImpl.java), we shouldn't cast the Long to an Integer.

**Comment by DvirDukhan** [comment]
@xujiaxj 
a fix has been merged to master branch, so you validate with this branch
I will release a new version soon

**Comment by xujiaxj** [comment]
@DvirDukhan Thanks for the quick fix. Yes I verified that the fix worked. Kindly let me know when you release the newer version.
